/*
 * This source file was generated by the Gradle 'init' task
 */
package taller5;

public class App {
    
    public static void main(String[] args) {
        
        try {
             System.out.println("Resultado del ejercicio 1 (Adivinar Número):");
            Adivinar_Numero();

           
            System.out.println("Resultado del ejercicio 2 (Simular Ventas):");
            System.out.println(Simular_ventas());

          
            System.out.println("Resultado del ejercicio 3 (Calcular Empaque):");
            System.out.println(Calcular_empaque(500)); 

         
            System.out.println("Resultado del ejercicio 4 (Jugar 21):");
            Jugar_21(3); 
            
        } 
        
        catch (Exception e) {
               System.out.println("ocurrio un error" \n e.toString);
                              
        }
    }


    /*
    
        1.	Desarrolle un algoritmo e impleméntelo en Java que: le pida al usuario un número entero positivo 
        entre 1000 y 9999. En un ciclo genere números de manera aleatoria y cuente los intentos que hizo antes 
        de hallar el número exactamente.
        
    
    */ 

    public static int Adivinar_Numero()throw Exception{
    try {
            Scanner sc = new Scanner(System.in);
            Random random = new Random();
            int numeroUsuario = 0;
            int numeroAleatorio;
            int intentos = 0;

            System.out.println("Ingresa un número entero positivo entre 1000 y 9999: ");

            if (numeroUsuario < 1000 || numeroUsuario > 9999) {
                throw new Exception("El número debe estar entre 1000 y 9999.");
            }

          
            do {
                numeroAleatorio = random.nextInt(9000) + 1000; // Genera entre 1000 y 9999
                intentos++;
            } while (numeroAleatorio != numeroUsuario);

            System.out.println("Número encontrado después de " + intentos + " intentos!");

        } catch (Exception e) {
            System.out.println("Error: ");
        }
    }



    /* 
     
        2.	Se requiere una función en java que simule las ventas de tres años para un almacén. Para cada año, deberá generar 
        un aleatorio para cada mes hasta completar los 12 meses. La función se llamará Simular_ventas, y debe retornar un String 
        al final que muestre las ventas de cada año, así:
        
            Año 1
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 1:  $##.###.###
            
            Año 2
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 2: $##.###.###
            
            Año 3
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###

            Total ventas Año 3: $##.###.###
            
            Investigue sobre la clase DecimalFormat para mostrar bien la salida. 
            import java.text.DecimalFormat;
            DecimalFormat form_pesos = new DecimalFormat("$#,###.00");

        
      
    */
    public static String Simular_ventas(){
    try {
            Random random = new Random();
            DecimalFormat form_pesos = new DecimalFormat("$#,###.00");
            String resultado = "";

            /
            for (int año = 1; año <= 3; año++) {
                resultado += "Año " + año + "\n";
                double totalVentasAño = 0;
                for (int mes = 1; mes <= 12; mes++) {
                    double ventasMes = random.nextDouble() * 1000000 + 500000; 
                    totalVentasAño += ventasMes;
                    resultado += "Ventas Mes " + mes + ": " + form_pesos.format(ventasMes) + "\n";
                }
                resultado += "Total ventas Año " + año + ": " + form_pesos.format(totalVentasAño) + "\n\n";
            }

            return resultado; // Devolvemos la cadena final

        } catch (Exception e) {
            
            return "Error al generar las ventas: " + e.getMessage();
        }
}
    



    /*  
     
        3.	En una fábrica se tiene el siguiente patrón de empaque: En una estiba(o pallet) caben 16  cajas y en cada caja, 
        caben 30 bombillas. Desarrolle una función que se llame: Calcular_empaque que: reciba como argumento la cantidad de 
        bombillas que se deben empacar y a partir de allí: calcule cuántas cajas necesita, cuántas estibas o pallets necesita. 
        Luego escriba lo siguiente: 

        Para ### bombillas, se necesitan ## cajas y ## pallets. Se quedan ### bombillas sin empacar. Se empacará así:

        Pallet 1 --> Caja1, Caja2……,Caja16
        Pallet2 -->  Caja17, Caja18…..Caja 32
        .
        Pallet n -- > Caja m, caja m+1…..
        
        La función retornará un texto, con la información anterior. Pruebe la función llamándola desde el programa principal: solicite al usuario el número de bombillas e invoque la función para imprimir en el main, los resultados.



    */


    public static String Calcular_empaque(int bombillas) {
        try {
            
            final int BOMBILLAS_POR_CAJA = 30;
            final int CAJAS_POR_PALLET = 16;

            
            int cajasNecesarias = bombillas / BOMBILLAS_POR_CAJA;
            int bombillasRestantes = bombillas % BOMBILLAS_POR_CAJA;
            int palletsNecesarios = cajasNecesarias / CAJAS_POR_PALLET;
            int cajasRestantes = cajasNecesarias % CAJAS_POR_PALLET;

     
            String resultado = "Para " + bombillas + " bombillas, se necesitan " + cajasNecesarias + " cajas y " + palletsNecesarios + " pallets.\n";
            resultado += "Se quedan " + bombillasRestantes + " bombillas sin empacar.\n";
            resultado += "Se empacará así:\n";

     
            int cajaActual = 1;
            for (int pallet = 1; pallet <= palletsNecesarios; pallet++) {
                resultado += "Pallet " + pallet + " --> ";
                for (int caja = 1; caja <= CAJAS_POR_PALLET; caja++) {
                    resultado += "Caja" + cajaActual;
                    if (caja < CAJAS_POR_PALLET) {
                        resultado += ", ";
                    }
                    cajaActual++;
                }
                resultado += "\n";
            }

            if (cajasRestantes > 0) {
                resultado += "Pallet " + (palletsNecesarios + 1) + " --> ";
                for (int caja = 1; caja <= cajasRestantes; caja++) {
                    resultado += "Caja" + cajaActual;
                    if (caja < cajasRestantes) {
                        resultado += ", ";
                    }
                    cajaActual++;
                }
                resultado += "\n";
            }

            return resultado;

        } catch (Exception e) {
            return "Error: ocurrió un problema con el cálculo.";
        }
    }
    

    /* 
    

        4.	En un juego, cada jugador tiene 3 intentos para sacar cartas de una baraja. Las cartas van numeradas entre 1 y 10. 
        Una función Jugar_21, deberá simular el juego para una cantidad de usuarios que enviará el usuario desde el main entre 1 y 6.

        Para cada uno de los jugadores, el programa le calculará 3 cartas al azar y al final imprimirá el juego para cada jugador basado en las siguientes reglas: 
        
        Si saca 21 exactos: juego perfecto
        Si saca más de 21: se pasó
        Si saca menos de 21: faltaron puntos

        La función deberá imprimir los puntos de cada jugador junto con la regla anterior, como muestra el ejemplo:

        Jugador X, puntos 21 -- > juego perfecto
        Jugador Y, puntos 26 -- > se pasó
        .
        .


    */

    public static void Jugar_21(int jugadores) {
        
        
        try {
            Random random = new Random();
            
            for (int i = 1; i <= jugadores; i++) {
                int puntos = 0;

                
                for (int intento = 1; intento <= 3; intento++) {
                    int carta = random.nextInt(10) + 1; 
                    puntos += carta; 
                }

                System.out.print("Jugador " + i + ", puntos " + puntos + " --> ");
                
                
                if (puntos == 21) {
                    System.out.println("juego perfecto");
                } else if (puntos > 21) {
                    System.out.println("se pasó");
                } else {
                    System.out.println("faltaron puntos");
                }
            }
        } catch (Exception e) {
            System.out.println("Error: ocurrió un problema al calcular los puntos.");
        }
    }
}







}
